### PR TITLE
Handle rapid navigation

### PR DESCRIPTION
**Pull request by hirasso**
Fixes the bug described in #187 .

This attempt addresses the described bug by doing two things:

1. Don't execute `renderPage` if `page.url` doesn't match `getCurrentUrl()`:

```js
const isCurrentPage = this.getCurrentUrl() === page.url;
if( !isCurrentPage ) return;
```
2. Remove all swup-related html-classes on popstate, if `animateHistoryBrowsing` is `false`:
```js
if( !this.options.animateHistoryBrowsing ) {
  document.documentElement.classList.remove('is-animating');
  cleanupAnimationClasses();
}
```
I tried to run cypress on this, but I can't get it to work / I have never used it. Manual testing looked fine, though.

### CODE REVIEW

**Comment by daun** [comment]
We're probably over-engineering this. If we set an `isAnimating` flag on the instance and force a normal browser load (`window.location = *`) for all links that are clicked while animating, we get rid of all the edge cases and keep complexity to a minimum. What do you think?

**Comment by hirasso** [comment]
This fix doesn't add a lot of complexity and it works fine for me. Actually, I was quite surprised that the check for the still-current-url in `renderPage` wasn't there, already.

Have you tested it?

**Comment by hirasso** [comment]
I uploaded a little test site to my server:

https://test.rassohilber.com/swup-handle-rapid-navigation/test/

The transition is extra long there, so that you have plenty of time to hit the browser back/forward buttons ;)

I made the `swup` instance available in the `window` object, so you can change `animateHistoryBrowsing` at runtime: 
```js
swup.options.animateHistoryBrowsing = true
```

**Comment by daun** [comment]
It's working surprisingly well! And you're right, it's not that complex. All the whitespace has changed from tabs to spaces, that's why it looks more complex than it is 🌝 Maybe you can fix that?

One edge case to keep in mind: 301/302 redirects. Can we test that as well?

**Comment by hirasso** [comment]
Haha sorry, the whitespace problem again 🙈 ...I'll try to fix it. 

Regarding 301/302 redirects: We don't want this to happen, either, if the requested URL has changed. Hence the early conditional return in `renderPage`.

**Comment by daun** [comment]
So what happens if I click on /info/ and the server redirects to /info/about/? Does the current behavior change or will it abort at some point?

**Comment by hirasso** [comment]
If you wait for the page to load, the current behavior stays like is. If you navigate somewhere else before the page is loaded, any detected redirect is being ignored. We don't need the result right now anymore, after all.

**Comment by daun** [comment]
What I meant is: does that new `currentUrl()` vs. `page.url` check also work in case of redirects?

**Comment by hirasso** [comment]
Yes, `page.url` is not being altered by a redirected server response, so it should work. Haven't tested it, though.

**Comment by daun** [comment]
Great, I'll check it out locally.

**Comment by hirasso** [comment]
I managed to get prettier to work. Just ran it on the two files I modified, it cleaned up my code, but also quite a bit of code that wasn't part of this PR.

```shell
npx prettier --write ./src/modules/renderPage.js
npx prettier --write ./src/index.js
```
We should definitely think about introducing some automated invocation of `prettier` IMO.

**Comment by daun** [comment]
Can confirm this is working nicely. Tests are passing and it works for normal clicks, popstate and redirects. Great work 🥯

**Comment by daun** [comment]
Can you create a branch on the swup repo itself, not your fork? I think that's why the CI build isn't happening.

**Review by daun — APPROVED** [review]

**Comment by hirasso** [comment]
Closing this PR in favor of https://github.com/swup/swup/pull/464

**Pull request closed without merging**
