### PR TITLE
Simplify container replacement

### PR DESCRIPTION
**Pull request by daun**
**Description**

Prototype for simplifying how content containers are replaced.

- Containers are parsed from selectors right before they will be replaced
- This will allow modifying the containers on-the-fly, e.g. by the upcoming fragment plugin or by users themselves
- Every container selector will match a single element (querySelector instead of querySelectorAll)
- No need to add `data-swup` attributes on the containers anymore
- We only need the `url` and raw `html` from the xml request object
- Everything else (document title, body class) can be extracted just-in-time
- Remove `responseURL` and switch to more universal `url` everywhere to allow easier switch to `fetch`
- We don't need `getPageData` and `getDataFromHtml` helpers anymore
- Reduces bundle size by 0.25k

Caveats

- This only works if we assume we stop supporting custom payloads
- The body class plugin needs a slight update (see updated test file)

**Checks**

- [x] The PR is submitted to the `master` branch
- [x] The code was linted before pushing (`npm run lint`)
- [x] All tests are passing (`npm run test`)
- [ ] ~~New or updated tests are included~~
- [ ] The documentation was updated as required

### CODE REVIEW

**Comment by daun** [comment]
This would probably fix #651

**Comment by hirasso** [comment]
I like it! Should this maybe be a PR to the `next` branch?

**Comment by daun** [comment]
@hirasso It probably should, but I'm not sure what the current state of the `next` branch is. Is everything on it approved, but only approved for the next major version? In that case, I should rebase on the `next` branch...

**Comment by hirasso** [comment]
As far as I know, the next branch wasn't updated since the last major release.

**Comment by daun** [comment]
Rebased current master onto next branch...

**Comment by daun** [comment]
Crap, we've merged some cache logic improvements since the latest master but never released it...

**Comment by daun** [comment]
Will look into this next week...

**Comment by hirasso** [comment]
Oops! Good find @daun  🔍 
Thank you for looking into it!

**Comment by daun** [comment]
Incorporated the previous cache upgrades, up-to-date again.

**Pull request merged**
