### PR TITLE
Manual scroll restoration from history state

### PR DESCRIPTION
**Pull request by daun**
Most routing libraries currently store the scroll position in the history state and manually restore it from there.

**Advantages**

- Programmatically read and manipulate the stored position
- Control over the exact point in time when to restore the scroll position
- No artificial separation between animated and non-animated (history) visits

**Prior art**

- Turbo: [save to history](https://github.com/hotwired/turbo/blob/main/src/core/session.js#L197)
- pjax: [save to history](https://github.com/MoOx/pjax/blob/master/lib/proto/handle-response.js#L23)
- Astro: [save to history](https://github.com/withastro/astro/blob/052d3271d4a9f12b88897c57cdfa134cb83c9eee/packages/astro/src/transitions/events.ts#L168)
- Livewire: [save to body attribute](https://github.com/livewire/livewire/blob/main/js/plugins/navigate/scroll.js#L3)

**Description**

- Remember scroll position in history state
- Restore scroll position from history state
- Completely disable browser scroll restoration
- Create two hooks: `scroll:store` when saving position, `scroll:restore` when restoring position
  - Makes it extendable to support arbitrary scroll containers (to be managed by Scroll Plugin)
- Currently uses debounced `scroll` function to update position when scrolling stops
  - There is the new [scrollend event ](https://developer.mozilla.org/en-US/docs/Web/API/Document/scrollend_event)but it's not 100% supported unfortunately and [the polyfill is huge](https://github.com/argyleink/scrollyfills/blob/main/src/scrollend.js)

**To-do**

- Restore scroll position on reload (maybe a Scroll Plugin feature?)
- Implement proper tests
- Check if this breaks anything and needs to move into v5

**Checks**

- [x] The PR is submitted to the `master` branch
- [x] The code was linted before pushing (`npm run lint`)
- [x] All tests are passing (`npm run test`)
- [x] New or updated tests are included
- [ ] The documentation was updated as required

### CODE REVIEW

**Comment by daun** [comment]
Note to self: make scroll handler passive.

**Comment by hirasso** [comment]
Another note: Check if this breaks scroll position restoration if using `resolveUrl`.

**Comment by daun** [comment]
@hirasso Right! We'll probably need to check this together on a call, the resolve-url logic is still a bit mysterious to me 🙃

**Comment by daun** [comment]
@hirasso I think this one is ready for review :)

Could you check in one of your projects using `resolveUrl` if this makes any difference in behavior?

**Comment by daun** [comment]
Closing in favor of implementing this in the Scroll Plugin for advanced use cases.

**Comment by daun** [comment]
Tracked in [#84](https://github.com/swup/scroll-plugin/issues/84)

**Pull request closed without merging**
