### PR TITLE
feat: support body container

### PR DESCRIPTION
**Pull request by Grafikart**
Accept body as a container

### CODE REVIEW

**Comment by Grafikart** [comment]
I also added the page to the loadedEvent since it can be used to add more behaviours

**Comment by gmrchk** [comment]
Hi, swup relies on body element in some cases, like the [Body Class plugin](https://swup.js.org/plugins/body-class-plugin) or for themes as well, where replacing the whole body would break it all (at least for themes for sure), so those would be incompatible when this option would be set to `body`. Instead of replacing the whole body, swup goes for replacing any parts of the page, even if it means the whole page being wrapped in one container. 

I think this would complicate thing in some areas, and quite unnecessarily. Do you have some specific example where the whole body just needs to be replaced, and classic containers can't be used?

**Comment by gmrchk** [comment]
Kudos for the `pageLoaded` event tho, could be very useful in some cases.

**Comment by gmrchk** [comment]
Unfortunately, I'll have to close this as it's too much of a breaking change without actual feedback of this being requested by people. I have updated the docs to include a warning.

Thank for all your work!

**Pull request closed without merging**
