### PR TITLE
Cache control per visit

### LINKED ISSUE #763: Allow bypassing cache for load and save
**Describe the problem**

There should be a way of disabling the cache to help with forms, especially on POST requests.

1. Bypass cache on load: ignore any previously cached pages
2. Skip cache on save: do not store the response in the cache

**Describe the proposed solution**

1. Extend `FetchOptions` with two parameters, e.g.
  a. `bypassCache` and `skipCacheSave` with default `false`
  b. `getFromCache` and `saveToCache` with default `true`
3. Extend `FetchOptions` with a `cacheControl` parameter that mimics the [Cache-Control header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control?retiredLocale=de#directives)
4. Directly read from the request headers and interpret the `Cache-Control` header ourselves

**Alternatives considered**

- Manually clearing the cache before a request
- Manually clearing the cache after a request

**How important is this feature to you?**

- [ ] Nice to have
- [x] Would make my life a lot easier
- [ ] I cannot use swup without it

### PR DESCRIPTION
**Pull request by daun**
**Description**

- Store cache settings in visit object: `{ read: true, write: true }`
- Add cache option to `swup.navigate`:  `{ read?: true, write?: true }`
- Only cache responses of `GET` requests
- Increases bundle size by 100 bytes

**Drive-by changes**

- Remove `this.cache.clear()` from `renderPage` as it was meant for Preload Plugin which now requires the cache

**Checks**

- [x] The PR is submitted to the `master` branch
- [x] The code was linted before pushing (`npm run lint`)
- [x] All tests are passing (`npm run test`)
- [x] New or updated tests are included
- [ ] The documentation was updated as required

**Additional information**

Closes #763

### CODE REVIEW

**Comment by hirasso** [comment]
Amazing!

I stumbled a bit upon the boolean for both behaviours. Without knowing the internals, I would think that this would only disable loading from the cache. I wouldn't think about saving to the cache.

**Comment by daun** [comment]
@hirasso Do you think a boolean false should disable reads but keep writes enabled?

**Comment by hirasso** [comment]
I think I would force users to think about what they want and remove the wildcard boolean altogether

**Comment by daun** [comment]
I've removed the boolean option. Since we need to sanitize the value to an object during runtime anyway, technically booleans still work the same, however they'll now throw an error in TS projects.

**Comment by daun** [comment]
I've pushed a change to only cache `GET` requests in general to align swup with browser behavior.

**Comment by daun** [comment]
The tests are really flaky here; they work locally every time but fail intermittently in CI. Will need debug them.

**Comment by daun** [comment]
Pushed a fix for the flaky tests — seems to be working now.

**Comment by hirasso** [comment]
Huh? How did you come up with that fix?! Can you explain why this makes the tests less flaky?😵‍💫😄

**Comment by daun** [comment]
We were only checking if the new URL was matching the expected page, but that could match even before the hooks have run since the URL gets updated before any requests are sent. Now we're making sure the content was updated as well before continuing.

**Review by hirasso — APPROVED** [review]

**Comment by hirasso** [comment]
Interesting!

**Pull request merged**
