### PR TITLE
Move path classnames to route-name plugin

### PR DESCRIPTION
**Pull request by daun**
**Description**

- Proposal to stop adding `to-{url}` classnames by default in swup
- Those classnames should and could be optional
- The [route-name](https://github.com/swup/route-name-plugin) plugin was [just updated](https://github.com/swup/route-name-plugin/pull/2) to start adding those classnames, fitting its purpose
- We'll slim down the core while providing a clear alternative for people migrating to swup 3

**Before: swup only**

```html
<html class="is-animating to-b">
```

**After: swup only**

```html
<html class="is-animating">
```

**After: swup with route-name plugin**

```html
<html class="is-animating from-a to-b">
```

**Upgrade path**

```js
const swup = new Swup({
  plugins: [new SwupRouteNamePlugin({ paths: true })]
})
```

**Checks**

- [x] The PR is submitted to the `next` branch
- [x] The code was linted before pushing (`npm run lint`)
- [x] New or updated tests are included
- [x] All tests are passing (`npm run test`)
- [x] The documentation was updated as required

### CODE REVIEW

**Comment by hirasso** [comment]
If I'm not mistaken, JS Plugin expects the route name classes to be added by core. If we extract the functionality, we would create plugin peer dependencies.

**Comment by daun** [comment]
@hirasso Could you point me to where it expects those classes to be set? I haven't used the js plugin myself so I'm not too familiar with it.

**Comment by hirasso** [comment]
@daun If you look at the documentation of JS Plugin:

```js
const options = [
  {
    from: '(.*)', // matches any route
    to: '(.*)', // matches any route
    out: next => next(), // immediately continues
    in: next => next() // immediately continues
  }
];
```
It's an array of `from/to` directives. You can use any route in the `from` and `to` properties of each directive.

Actually, JS Plugin would also help with waiting for any transition to start/finish (you have written about that in #561), so probably worth checking it out :)

**Comment by daun** [comment]
@hirasso I see, seems like that's not related then. The JS plugin does its own parsing of the URL into route names. It doesn't add or require classnames on the `html` element. All this PR does is make swup stop adding the `to-{url}` classnames to the HTML and move that feature to the route-name plugin instead. There's some overlap between the js and route-name plugin in that they both use path-to-regexp to parse urls into named routes, but that's coincidental.

Thanks for the pointer about the delay issue! I'll need to see if that helps with that.

**Comment by hirasso** [comment]
@daun great, feels like we are gaining a broader overview of swup+plugins step by step 🐾

**Review by hirasso — APPROVED** [review]
Looks great, lets gooo

**Pull request merged**
