### PR TITLE
feat: automerge dependabot PRs

### PR DESCRIPTION
**Pull request by hirasso**
**Description**

A new attempt to automate the process of merging dependabot PRs.

- for now only for `patch` version bumps
- includes a manual trigger for testing it as soon as we have merged it
- we currently have a whole bunch of open PRs, so this would be a nice chance to test the action
- if it works, we can inherit the action within the plugins

**Checks**

- [x] The PR is submitted to the `master` branch
- [x] The code was linted before pushing (`npm run lint`)

### CODE REVIEW

**Comment by daun** [comment]
Nice! Do you think we'd regret starting with `minor` right away? I'm quite confident in our tests at this point...

**Comment by hirasso** [comment]
Alright, it's `target: minor` now

**Review by daun — APPROVED** [review]
🤖

**Comment by hirasso** [comment]
This worked nicely. I'll proceed with extending the action in fragment-plugin

**Pull request merged**
