### PR TITLE
feat: queue navigation

### PR DESCRIPTION
**Pull request by hirasso**
Related: #825 

**Description**

- queue the next visit during running visits
- Pass around the visit object instead of relying on the global `swup.visit`

**TODO**

- [x] Convert the `Visit` object to a class
- [x] Fix all errors that prevent functional tests from passing
- [x] Handle `hooks.call` and `hooks.callSync` with missing `visit` arg

**Checks**

- [x] The PR is submitted to the `master` branch
- [x] The code was linted before pushing (`npm run lint`)
- [x] All tests are passing (`npm run test`)
- [x] New or updated tests are included
- [ ] The documentation was updated as required

### CODE REVIEW

**Comment by daun** [comment]
Note: I have a feeling the below code contains a bug. The check for `!url || url === from` probably also triggers when going to the homepage, as that should be an empty string here. The second part should suffice, as we're already sanitizing everything inside `Location`. Need to check, though.

```ts
this.hooks.callSync('link:click', visit, { el, event }, () => {
  const from = visit.from.url ?? '';
  event.preventDefault();
  if (!url || url === from) {
    /* ... */
  }
});
```

**Comment by daun** [comment]
Tests are passing again 🎉 The legacy argument order is now also handled correctly.

**Comment by daun** [comment]
>   if (!url || url === from)

To follow up on this after some research: `URL.pathname` is never empty and will always have a leading `/` in front of it, so the comparison here is safe and doesn't need addressing :)

**Comment by hirasso** [comment]
Woah, I actually also was surprised by this. PR towards the MDN article? :)

**Pull request closed without merging**
