### PR TITLE
Disable caching of initial page

### LINKED ISSUE #475: Delay caching first page until after DOM load event
When a first page-load has `<style>` tags in a container used by Swup, it will not add them to the cache. Navigating back will result in the page not having the `<style>` tags that it initially existed.

This issue does not present itself with subsequent page-loads, loaded by mouse-over, for example. It that case, the tags get added to the cache properly.

### Workaround
For now, you can turn off the cache:
```js
const options = {
  cache: true
}
```

This isn't ideal (the caching Swup does is the reason I'm using it, and it rocks when it works), but this will prevent any lost styles. The issue is especially pungent on Wordpress 5.9+ sites that insert dynamic `<style>` blocks.

### PR DESCRIPTION
**Pull request by daun**
- Disable caching of initial page state to avoid modified dom being cached
- Logic is moved to preload plugin: see [#29](https://github.com/swup/preload-plugin/pull/29)
- Replaces #478 
- Fixes #475
- Waiting on #484 to fix test suite

### CODE REVIEW

**Review by hirasso — DISMISSED** [review]

**Comment by hirasso** [comment]
Hmm, something off with the tests here. At first, I thought it was related to the cache tests, but it doesn't seem so. The error message I am getting also doesn't help a lot:
```shell
1) "before each" hook for "should transition forward to page 2 on popstate"
```

**Comment by daun** [comment]
@hirasso Disabling the cache seems to break the tests as well, even without the changes in this PR. I'll look into it.

**Comment by daun** [comment]
Phew. This one isn't easy. I'd love to fix this for the next release but there's no rush I guess.

**Comment by daun** [comment]
@hirasso With the recent updates to the test suite, the tests are passing again. Please re-approve whenever you get the chance.

**Review by hirasso — APPROVED** [review]

**Pull request merged**
